### PR TITLE
Added LGPL-friendly JewishCalendar based off native .NET HebrewCalendar

### PR DESCRIPTION
**Pull request by dakom**
Bunch of other changes too... some additional tests, some modifications to HebrewFormatter...

The main idea with JewishCalendar is like HebrewCalendar, pass DateTime to everything :)

### CODE REVIEW

**Comment by Yitzchok** [comment]
How do we know if this modification is still considered under the original GPL'd version?

**Comment by dakom** [comment]
I asked Eliyahu to take a quick glance. He said that the main issue was the parsha stuff and at a non-thorough glance this seems to be fine

**Comment by Yitzchok** [comment]
OK great I'll merge it in over the next few days.



Thanks so much

**Comment by Yitzchok** [comment]
Merged

**Pull request closed without merging**
